# Credenciales de la Base de Datos Neon
DB_USER = "tu_usuario_neon"
DB_PASSWORD = "tu_contraseña_neon"
DB_HOST = "ep-plain-moon-123456.eu-central-1.aws.neon.tech"
DB_PORT = "5432"
DB_NAME = "neondb"

# Claves de APIs
RACING_API_KEY = "bbc95a23a8msh91989a027582f89p1b7715jsn287e79202cdc"
GEMINI_API_KEY = "AIzaSyCh0w5VNQvretj5RWbBijiD78KEWsD_k1g"

# Credenciales de Login para la App
APP_USERNAME = "alberto29117"
APP_PASSWORD = "Milkamilka10."
