# Credenciales de la Base de Datos Neon
DB_USER = "alberfp92"
DB_PASSWORD = "Chiflasti7777."
DB_HOST = "postgresql://neondb_owner:npg_Xzukr5ZiYN4S@ep-crimson-cloud-a21mwx0w-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
DB_PORT = "5432"
DB_NAME = "App_caballos"

# Claves de APIs
RACING_API_KEY = "bbc95a23a8msh91989a027582f89p1b7715jsn287e79202cdc"
GEMINI_API_KEY = "AIzaSyCh0w5VNQvretj5RWbBijiD78KEWsD_k1g"

# Credenciales de Login para la App
APP_USERNAME = "alberto29117"
APP_PASSWORD = "Milkamilka10."
